apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: demo-pvc
    namespace: demo
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: pvc-backup
    sessionHistoryLimit: 
    scheduler: 
      schedule: "*/2 * * * *"
      jobTemplate: 
        backoffLimit: 1
    repositories: 
    - name: pvc-backup
      backend: s3-storage
      directory: /pvc-backup
      encryptionSecret:
       name: encry-secret 
       namespace: demo
      deletionPolicy: WipeOut 
    addon:
      name: pvc-addon
      tasks:
      - name: pvc-backup
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0
    retryConfig:
      maxRetry: 2
      delay: 1m