apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: cluster-resources-backup
  namespace: demo
spec:
  backends:
    - name: s3-storage
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: cluster-resources-backup
      sessionHistoryLimit: 3
      scheduler:
        # schedule: "0 12 * * *" # Daily once at 12 p.m
        schedule: "*/5 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: cluster-resources
          backend: s3-storage
          directory: /manifest/cluster-resources
          encryptionSecret:
           name: encrypt-secret
           namespace: demo
      addon:
        name: kubedump-addon
        tasks:
          - name: manifest-backup
        jobTemplate:
          spec:
            serviceAccountName: cluster-resource-reader