apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: mysql-v8-0-3
spec:
  backupTasks:
  - name: mysql-backup
    singleton: true
    function: mysql-backup
    driver: Restic
    parameters:
    - name: args
      usage: Specifies the database args 
      required: false
      default: "--all-databases --set-gtid-purged=OFF"
  restoreTasks:
  - name: mysql-restore
    singleton: true
    function: mysql-restore
    driver: Restic
    parameters:
    - name: mysql-args
      usage: Specifies the database args 
      required: false
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-backup
spec:
  image: ashraf10039/mysql:refactor_8.0.21_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --mysql-args=${args:=}
  - --db-version=8.0.3
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mysql-restore
spec: 
  image: ashraf10039/mysql:refactor_8.0.21_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --mysql-args=${args:=}
  - --db-version=8.0.3