apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: pvc-backup
spec:
  image: anisurrahman75/pvc:v0.1.0-rc.0_linux_amd64
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --paths=${paths:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata: 
  name: pvc-restore
spec: 
  image: anisurrahman75/pvc:v0.1.0-rc.0_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: pvc-addon
spec:
  backupTasks:
    - name: pvc-backup
      function: pvc-backup
      singleton: true 
      driver: Restic #Restic, WalG
      parameters:
      - name: paths
        default: /kubestash/data   
        usage: Specifies the default path that will be used for backup.
        required: true
      volumeMounts:
      - name: kubestash-volume
        mountPath: /kubestash/data
      volumeTemplate:
      - name: kubestash-volume
        source:
          persistentVolumeClaim:
            claimName: ${PVC_NAME}
  restoreTasks:
    - name: pvc-restore
      singleton: true
      function: pvc-restore
      driver: Restic
      volumeMounts:
      - name: kubestash-volume
        mountPath: /kubestash/data
      volumeTemplate:
      - name: kubestash-volume
        source:
          persistentVolumeClaim:
            claimName: ${PVC_NAME} 
    - name: clone-data-volume-restore
      singleton: false 
      function: pvc-restore
      driver: Restic