apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: redis-addon
spec:
  backupTasks:
  - name: redis-backup
    singleton: true
    function: redis-backup
    driver: Restic
    parameters:
    - name: args
      usage: Specifies the database args for taking backup
      required: false
  restoreTasks:
  - name: redis-restore
    singleton: true
    function: redis-restore
    driver: Restic
    parameters:
    - name: args
      usage: Specifies the database args for restore
      required: false
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: redis-backup
spec:
  image: neajmorshad/redis:neaj-redis_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --redis-args=${args:=}

--- 

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: redis-restore
spec:
  image: neajmorshad/redis:neaj-redis_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --redis-args=${args:=}

