apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mongo-sh
  namespace: demo
spec:
  version: 5.0.23
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 2
    shard:
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard