apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: pvc-restoresession
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: restored-pvc
    namespace: demo
  dataSource:
    repository: pvc-demo-gcs
    snapshot: latest
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: LogicalBackupRestore
