apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: es-db-backup
spec:
  target:
    apiGroup: kubedb.com
    kind: Elasticsearch
    namespace: default
    name: sample-es
  backends:
  - name: s3-storage
    storageRef:
      name: s3-storage
      namespace: default
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: frequent-backup
    sessionHistoryLimit: 10
    scheduler:
      schedule: "*/1 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: s3-repo-es
      backend: s3-storage
      directory: /sample/kubestashs/elastic
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: default
    addon:
      name: elasticsearch-addon-interim
      tasks:
      - name: LogicalBackup
        # addonVolumes:
        # - name: ${INTERIM_VOLUME}
        #   source:
        #     volumeClaimTemplate:
        #       spec:
        #         accessModes:
        #         - ReadWriteOnce
        #         resources:
        #           requests:
        #             storage: 10Gi
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0