apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-mysql-data
  namespace: demo
spec:
  task:
    params:
    - name: args
      value: --set-gtid-purged=OFF --no-create-info --all-databases --ignore-table=kubedb_system.kubedb_write_check
    - name: HOSTNAME
      value: data
  schedule: "*/5 * * * *"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mysql
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
