apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: sample-mysql-2
  namespace: demo
spec:
  version: "8.0.35"
  replicas: 1
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  deletionPolicy: WipeOut