kind: Pod
apiVersion: v1
metadata:
  name: pod-1
spec:
  containers:
  - name: busybox
    image: busybox
    # command: ["/bin/sh", "-c","echo 'hello from pod 1.' > /sample/data/hello.txt && sleep 3000"]
    volumeMounts:
    - name: my-volume
      mountPath: /sample/data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: csi-pvc