kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-data
  namespace: demo
  annotations:
        populator.kubestash.com/app-name: kubestash-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: storage.kubestash.com
    kind: Snapshot
    name: deployment-volume-snapshot-volumlume-snapshot-backup-1705332120
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-config
  namespace: demo
  annotations:
        populator.kubestash.com/app-name: kubestash-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: storage.kubestash.com
    kind: Snapshot
    name: deployment-volume-snapshot-volumlume-snapshot-backup-1705332120
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: copy-source-data
#   annotations:
#         populator.kubestash.com/app-name: kubestash-deployment
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   dataSourceRef:
#         apiGroup: storage.kubestash.com
#         kind: Snapshot
#         name: deployent-deployment-backup-workload-backup-1697703720
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: copy-source-config
#   annotations:
#         populator.kubestash.com/app-name: kubestash-deployment
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   dataSourceRef:
#         apiGroup: storage.kubestash.com
#         kind: Snapshot
#         name: deployent-deployment-backup-workload-backup-1697703720

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestash-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 3000
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
        - mountPath: /source/config
          name: source-config

        # - mountPath: /copy/source/data
        #   name: copy-source-data
        # - mountPath: /copy/source/config
        #   name: copy-source-config
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: source-data
      - name: source-config
        persistentVolumeClaim:
          claimName: source-config
      # - name: copy-source-data
      #   persistentVolumeClaim:
      #     claimName: copy-source-data
      # - name: copy-source-config
      #   persistentVolumeClaim:
      #     claimName: copy-source-config