apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-target-pvc
  namespace: demo
spec:
  # storageClassName: csi-standard-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo
spec:
  containers:
  - name: busybox
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args: 
    - |
      echo "sample_data" > /target/mountpath/data.txt
      sleep 30000
    securityContext:
      # allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      # capabilities:
      #   drop:
      #     - ALL
    volumeMounts:
    - name: my-volume
      mountPath: /target/mountpath
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: backup-target-pvc