apiVersion: v1
kind: Pod
metadata:
  name: tls-server-pod
  namespace: demo
  labels:
    app: my-tls-server
spec:
  containers:
    - name: tls-server
      image: anisurrahman75/server:5.2
      imagePullPolicy: Always
      ports:
        - containerPort: 8443
