apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: minio-storage
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      bucket: backupbucket
      endpoint: https://minio-service.default:9000
      secretName: minio-secret
      region: us-east-1
      prefix: sunny
      # insecureTLS: true
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false
  deletionPolicy: WipeOut
