apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: db-mongo-appbinding
  namespace: demo
spec:
  clientConfig:
    url: mongodb+srv://db-mongodb-nyc3-51766-8d62c6c1.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-51766
  secret:
    name: db-mongo-credentials-secret
  type: mongodb