apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: local-storage-with-emptydir
  namespace: demo
spec:
  storage:
    provider: local
    local:
      mountPath: /safe/data
      emptyDir: {}
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false 
  deletionPolicy: WipeOut
  # runtimeSettings:
  #   pod:
  #     securityContext:
  #       fsGroup: 65535
        