apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: nfs-storage
  namespace: demo
spec:
  storage:
    provider: local
    local:
      mountPath: /nfs/data
      nfs:
        server: 192.168.0.28 # IP to our NFS server
        path: /NFS-SERVER/backup-dir-1 # The exported directory
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false 
  deletionPolicy: WipeOut
  runtimeSettings:
    pod:
      securityContext:
        fsGroup: 65534