apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: pvc-storage
  namespace: demo
spec:
  storage:
    provider: local
    local:
      mountPath: /pvc/data
      persistentVolumeClaim:
        claimName: storage-pvc
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false 
  deletionPolicy: WipeOut
  runtimeSettings:
    pod:
      securityContext:
        fsGroup: 65535
        