apiVersion: v1
kind: Service
metadata:
  name: backup-job-service
  namespace: demo
spec:
  selector:
    job-name: mssql-db-backup-frequent-backup-1715933280
    kubestash.com/invoker-name: mssql-db-backup-frequent-backup-1715933280
    kubestash.com/invoker-namespace: demo
    kubestash.com/session-name: frequent-backup
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

