apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: default
spec:
  storage:
    provider: s3
    s3:
      bucket: kubestash
      region: us-east-1
      endpoint: us-east-1.linodeobjects.com
      secret: s3-secret
      prefix: sunny
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false 
  deletionPolicy: WipeOut