apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: namespace-resources-backup
spec:
  target: 
    apiGroup: ""
    kind: Namespace
    name: kube-system
  backends:
    - name: gcs-storage
      storageRef:
        namespace: default
        name: gcs-storage
      retentionPolicy:
        name: kubedump-rp
        namespace: default
  sessions:
    - name: cluster-resources-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/2 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: gcs-repo-namespace
          backend: gcs-storage
          directory: /kubedump/namespace
          deletionPolicy: WipeOut
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: default
      addon:
        name: kubedump-kubernetes-resources-addon
        tasks:
          - name: kubernetes-resources-backup
        jobTemplate:
          spec:
            serviceAccountName: cluster-resource-reader
