apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: daemonset-backup
  namespace: default
spec:
  target:
    apiGroup: apps
    kind: DaemonSet
    namespace: default
    name: daemonset-stash-demo
  backends:
    - name: s3-storage
      storageRef:
        apiGroup: storage.kubestash.com
        namespace: default
        kind: BackupStorage
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: default
  sessions:
    - name: workload-backup
      sessionHistoryLimit: 50
      scheduler: # CronJob specification
        schedule: "*/2 * * * *"
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 1
      repositories: # volume & volumeMount strategy.
        - name: dsemonset-backup
          backend: s3-storage
          directory: /daemonset
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: default
          deletionPolicy: WipeOut 
      addon:
        name: workload-addon
        tasks:
          - name: workload-backup
            targetVolumes:
             volumeMounts:
             - name:  source-data
               mountPath:  /source/data
            params:
             paths: /source/data
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
      retryConfig:
        maxRetry: 2
        delay: 1m
