apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: restored-redis
  namespace: demo
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  init:
    waitForInitialRestore: true
  storageType: Durable
  terminationPolicy: Delete
  version: 7.2.3