apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: gcs-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubestash
      prefix: /sunny/sample-statefulset
    storageSecretName: gcs-secret