apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: mssql-addon
spec:
  backupTasks:
    - name: logical-backup
      function: mssql-backup
      cleanerImage: anisurrahman75/mssqlserver-walg-plugin:init-backup-restore_linux_amd64
      driver: Restic
      function:
        task:
        cleaner:
      executor: Job
      singleton: true
      parameters:
        - name: databases
          usage: List of databases to backup.
          required: false
      volumeTemplate:
        - name: kubestash-tmp-volume
          usage: Holds temporary files and walG cache.
          source:
            emptyDir: {}
      volumeMounts:
        - name: kubestash-tmp-volume
          mountPath: /kubestash-tmp
  restoreTasks:
    - name: logical-backup-restore
      function: mssql-restore
      driver: Restic
      executor: Job
      singleton: true
      parameters:
        - name: databases
          usage: List of databases to restore.
          required: false
          default: "true"
      volumeTemplate:
        - name: kubestash-tmp-volume
          usage: Holds temporary files and walG cache.
          source:
            emptyDir: {}
      volumeMounts:
        - name: kubestash-tmp-volume
          mountPath: /kubestash-tmp

  cleanerTask:
    - name: kubestash-generic
      function: kubestash-generic-retention-policy # Refers corresponding function name.
      executor: Job
      driver: restic
      volumeTemplate:
        - name: kubestash-tmp-volume
          usage: Holds temporary files and walG cache.
          source:
            emptyDir: {}
      volumeMounts:
        - name: kubestash-tmp-volume
          mountPath: /kubestash-tmp
    
