apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: restored-postgres
  namespace: demo
spec:
  version: "16.1"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: Delete