apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: volume-snapshot-addon
spec:
  backupTasks:
    - name: workload-volume-snapshot-backup
      function: volume-snapshots-backup
      singleton: true
      driver: VolumeSnapshotter
      parameters:
      - name: snapshotClassName
  restoreTasks:
    - name: workload-volume-snapshot-restore
      function: volume-snapshots-restore
      singleton: true
      driver: VolumeSnapshotter

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: volume-snapshots-backup
spec:
  image: anisurrahman75/volume-snapshotter:f69f61ab_linux_amd64
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --snapshot-class-name=${snapshotClassName:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: volume-snapshots-restore
spec: 
  image: anisurrahman75/volume-snapshotter:f69f61ab_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --task-name=${taskName:=}  

---

apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: demo-retention
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 10
  usagePolicy:
    allowedNamespaces:
      from: All