apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: Deployment
    namespace: demo
    name: kubestash-deployment
  backends:
    - name: gcs-storage
      storageRef:
        namespace: demo
        name: gcs-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: deployment-backup
      sessionHistoryLimit: 5
      scheduler: # CronJob specification
        schedule: "*/2 * * * *"
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 1
      repositories: # volume & volumeMount strategy.
        - name: deployment-demo-gcs
          backend: gcs-storage
          directory: /deployment
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: demo
          deletionPolicy: WipeOut
      addon:
        name: workload-addon
        tasks:
          - name: LogicalBackup
            targetVolumes:
            params:
             paths: /source/data,/source/config
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
      retryConfig:
        maxRetry: 2
        delay: 1m
