apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: default
spec:
  target:
    apiGroup: apps
    kind: Deployment
    namespace: default
    name: kubestash-deployment
  backends:
    - name: s3-storage
      storageRef:
        apiGroup: storage.kubestash.com
        namespace: default
        kind: BackupStorage
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: default
  sessions:
    - name: workload-backup
      sessionHistoryLimit: 5
      scheduler: # CronJob specification
        schedule: "*/2 * * * *"
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 1
      repositories: # volume & volumeMount strategy.
        - name: demo-storage-0
          backend: s3-storage
          directory: /dep/sts-0
          encryptionSecret:
           name: encry-secret # some addon may not support encryption
           namespace: default
          deletionPolicy: WipeOut
      addon:
        name: workload-addon
        tasks:
          - name: workload-backup
            targetVolumes:
            params:
             paths: /source/data
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
      retryConfig:
        maxRetry: 2
        delay: 1m
