apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---

kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  namespace: demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"," echo sample_data > /sample/data.txt && sleep infinity"]
    volumeMounts:
    - name: my-volume
      mountPath: /sample
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: test-vol