apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sayed-vol
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn