apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn