apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-sayed-vol
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  dataSource:
    name: sayed-backup
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io