apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: sayed-backup
  namespace: demo
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: datadir-simple-2-configsvr-0