apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: sqlserver-0
  namespace: demo
spec:
  secret:
    name: mssqlserver-custom-auth
  type: mssql
  parameters:
    mssqlServerURLs:
      - 192.168.0.21:1433
  version: "2022-cu12"