kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-data
  annotations:
        populator.kubestash.com/app-name: kubestash-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  dataSourceRef:
        apiGroup: storage.kubestash.com
        kind: Snapshot
        name: deployent-deployment-backup-workload-backup-1696935960

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-config
  annotations:
        populator.kubestash.com/app-name: kubestash-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  dataSourceRef:
        apiGroup: storage.kubestash.com
        kind: Snapshot
        name: deployent-deployment-backup-workload-backup-1696935960

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: kubestash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 3000
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
        - mountPath: /source/config
          name: source-config
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: source-data
      - name: source-config
        persistentVolumeClaim:
          claimName: source-config