apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: bb
spec:
  storage:
    provider: s3
    s3:
      bucket: bytebuilders
      region: us-west-2
      endpoint: https://s3.us-west-2.amazonaws.com
      secretName: aws-s3-secret
      prefix: pvcs
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false
  deletionPolicy: WipeOut
