apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: badger-store-acaas-billing-processor-0
  namespace: ace
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: badger-store-acaas-billing-processor-0
    namespace: ace
  dataSource:
    namespace: bb
    repository: badgerdb-store-bytebuilders-shepherd-0
    snapshot: latest
    encryptionSecret:
      name: encrypt-secret
      namespace: bb
  addon:
    name: pvc-addon
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 0
    tasks:
    - name: logical-backup-restore
