apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo2
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: backup-target-pvc
    namespace: demo1
  backends:
  - name: pvc-backend
    storageRef:
      namespace: demo
      name: nfs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo3
  sessions:
  - name: two-minutes-backup
    sessionHistoryLimit: 3
    scheduler: # CronJob specification
      schedule: "*/1 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 0
    repositories: # volume & volumeMount strategy.
    - name: pvc-demo-pvc
      backend: pvc-backend
      directory: /backup-target-pvc
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: demo4
      deletionPolicy: WipeOut
    addon:
      name: pvc-addon
      tasks:
      - name: logical-backup
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0