apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: sample-mssqlserver
  namespace: demo
  labels:
    archiver: "true"
spec:
  healthChecker:
    timeoutSeconds: 100
  archiver:
    ref:
      name: mssqlserverarchiver
      namespace: demo
  version: "2022-cu16"
  replicas: 2
  authSecret:
    name: mssqlserver-custom-auth
    externallyManaged: true
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - demo
  tls:
    issuerRef:
      name: mssqlserver-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  podTemplate:
    spec:
      containers:
        - name: mssql
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: Evaluation  
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut