apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: pvc-backup
spec:
  image: anisurrahman75/pvc:cd5dfcc_linux_amd64
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --paths=${paths:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: pvc-restore
spec: 
  image: anisurrahman75/pvc:cd5dfcc_linux_amd64  
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoreSession=${restoreSession:=}
  - --snapshotName=${snapshotName:=}