apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: restored-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"

spec:
  volumeSnapshotClassName: csi-gce-pd-snapshot-class
  source:
    volumeSnapshotContentName: restored-snapshot-content