apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: restored-snapshot
spec:
  volumeSnapshotClassName: csi-gce-pd-snapshot-class
  source:
    volumeSnapshotContentName: restored-snapshot-content