apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: postgres-restoresession
  namespace: demo
spec:
  target:
    name: restored-postgres
    namespace: demo
    apiGroup: kubedb.com
    kind: Postgres
  dataSource:
    repository: gcs-postgres-repo
    snapshot: latest
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: postgres-addon
    tasks:
      - name: LogicalBackupRestore