apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: demo
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /var/opt/mssql
      name: data
  restartPolicy: Always
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-mssqlserver-ag-0