apiVersion: kubedb.com/v1alpha2
kind: MSSQLServer
metadata:
  name: restore-mssqlserver-ag
  namespace: demo
spec:
  healthChecker:
    timeoutSeconds: 200
  init:
    archiver:
      encryptionSecret:
        name: encrypt-secret
        namespace: demo
      recoveryTimestamp: "2024-12-24T06:50:15.657938Z" # "2024-08-14T22:43:41.300216Z" 
      fullDBRepository:
        name: mssqlserver-ag-archiver
        namespace: demo
  version: "2022-cu16"
  replicas: 2
  topology:
    mode: AvailabilityGroup
  tls:
    issuerRef:
      name: mssqlserver-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    clientTLS: false
  podTemplate:
    spec:
      containers:
        - name: mssql
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: Evaluation  
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut