apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: backup-target-pvc
    namespace: demo
  backends:
  - name: pvc-backend
    storageRef:
      namespace: demo
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: pvc-backup
    sessionHistoryLimit: 3
    scheduler: # CronJob specification
      schedule: "*/1 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
        template:
          spec:
            securityContext:
              runAsUser: 65535
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    repositories: # volume & volumeMount strategy.
    - name: pvc-demo-gcs
      backend: pvc-backend
      directory: /pvc-backup-demo
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: demo
      deletionPolicy: WipeOut 
    addon:
      name: pvc-addon
      tasks:
      - name: LogicalBackup
      # containerRuntimeSettings:
      #   securityContext:
      #     allowPrivilegeEscalation: false
      #     capabilities:
      #       drop:
      #         - ALL
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 65535
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    retryConfig:
      maxRetry: 0
      delay: 1m