apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: pvc-restoresession
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: restore-target-pvc
    namespace: demo
  dataSource:
    repository: pvc-demo-gcs
    snapshot: latest
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: LogicalBackupRestore
  runtimeSettings:
    pod:
      securityContext:
        runAsUser: 65535
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    container:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
