apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: pvc-backup
spec:
  image: anisurrahman75/pvc:4f7ec84_linux_amd64
  args:
  - backup
  - --scratchDir=/tmp
  - --namespace=${namespace:=default}
  - --backupSession=${backupSession:=}
  - --paths=${paths:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: pvc-restore
spec: 
  image: anisurrahman75/pvc:4f7ec84_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoreSession=${restoreSession:=}
  - --snapshotName=${snapshotName:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-backup
spec:
  image: anisurrahman75/workload:082ef12_linux_amd64
  args:
  - backup
  - --scratchDir=/tmp
  - --namespace=${namespace:=default}
  - --backupSession=${backupSession:=}
  - --paths=${paths:=}
  - --exclude=${exclude:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: workload-restore
spec: 
  image: anisurrahman75/workload:082ef12_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoreSession=${restoreSession:=}
  - --snapshotName=${snapshotName:=}
  - --exclude=${exclude:=}
  - --include=${include:=}