apiVersion: v1
kind: Service
metadata:
  name: nginx
  # namespace: demo
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubestash-statefulset
  # namespace: demo
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        command: ["/bin/sh", "-c"]
        args: 
        - |
          sleep 3000
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: restore-source-data
          mountPath: /source/data
        - name: restore-source-config
          mountPath: /source/config  
  volumeClaimTemplates:
  - metadata:
      name: restore-source-data
      annotations:
        populator.kubestash.com/app-name: kubestash-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-gce-pd
      dataSourceRef:
        apiGroup: storage.kubestash.com
        kind: Snapshot
        name: sts-volume-snapshot-volume-snapslume-snapshot-backup-1697781121
  - metadata:
      name: restore-source-config
      annotations:
        populator.kubestash.com/app-name: kubestash-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-gce-pd
      dataSourceRef:
        apiGroup: storage.kubestash.com
        kind: Snapshot
        name: sts-volume-snapshot-volume-snapslume-snapshot-backup-1697781121