apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: es-db-backup
spec:
  target:
    apiGroup: kubedb.com
    kind: MySQL
    namespace: default
    name: mysql-quickstart
  backends:
  - name: s3-storage
    storageRef:
      name: s3-storage
      namespace: default
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: frequent-backup
    sessionHistoryLimit: 10
    scheduler:
      schedule: "*/1 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: s3-repo-mysql
      backend: s3-storage
      directory: /sample/kubestash/mysql
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: default
      deletionPolicy: WipeOut
    addon:
      name: mysql-addon
      tasks:
      - name: LogicalBackup
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0