apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo-test
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubestash-restore-statefulset
  namespace: demo-test
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        command: ["/bin/sh", "-c"]
        args: 
        - |
          sleep 3000
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: source-data
          mountPath: /source/data
        - name: source-config
          mountPath: /source/config  
  volumeClaimTemplates:
  - metadata:
      name: source-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: source-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: statefulset-restoresession
  namespace: demo-test-2
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    namespace: demo-test
    name: kubestash-restore-statefulset
  dataSource:
    namespace: demo
    repository: statefulset-demo-gcs
    snapshot: latest
    encryptionSecret:
      name: encryption-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: workload-addon
    tasks:
    - name: logical-backup-restore
