apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: pvc-restoresession
  namespace: default
spec:
  dataSource:
    repository: demo-storage-0
    snapshot: latest
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: default
  addon:
    name: clone-pvc-addon
    tasks:
    - name: clone-pvc-restore
      # params:
      #   paths: /source/data