apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-standard-immediate