apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: es-restoresession
  namespace: demo
spec:
  target:
    name: restored-es
    namespace: demo
    apiGroup: kubedb.com
    kind: Elasticsearch
  dataSource:
    repository: gcs-es-repo
    snapshot: latest
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: elasticsearch-addon
    tasks:
      - name: LogicalBackupRestore