apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  annotations:
        populator.kubestash.com/app-name: kubestash-statefulset
spec:
  accessModes:
  - ReadWriteOnce
  # storageClassName: csi-gce-pd

  resources:
    requests:
      storage: 3Gi
      
  dataSourceRef:
    apiGroup: storage.kubestash.com
    kind: Snapshot
    name: pvc-pvc-backup-pvc-backup-169348560
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-pod-1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c","sleep 3000"]
    volumeMounts:
    - name: my-volume
      mountPath: /sample/data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: example-pvc