apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  # storageClassName: csi-gce-pd

  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: storage.kubestash.com
    kind: Snapshot
    name: pvc-demo-gcs-pvc-backup-two-minutes-backup-1705315440
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-pod-1
  namespace: demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c","sleep 3000"]
    volumeMounts:
    - name: my-volume
      mountPath: /sample/data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: example-pvc