apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: pvc-addon
spec:
  backupTasks:
    - name: pvc-backup
      function: pvc-backup
      singleton: true
      driver: Restic 
      parameters:
      - name: paths
        default: /kubestash/data #  This path will be backup
      volumeMounts:
      - name: kubestash-volume
        mountPath: /kubestash/data
      volumeTemplate:
      - name: kubestash-volume
        source:
          persistentVolumeClaim:
            claimName: ${PVC_NAME}

  restoreTasks:
    - name: pvc-restore
      singleton: false
      function: pvc-restore
      driver: Restic
      volumeMounts:
      - name: kubestash-volume
        mountPath: /kubestash/data
      volumeTemplate:
      - name: kubestash-volume
        source:
          persistentVolumeClaim:
            claimName: ${PVC_NAME}

    - name: clone-pvc-restore
      singleton: false
      function: pvc-restore
      driver: Restic




      