apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: host-pvc
    namespace: demo
  backends:
  - name: s3-storage
    storageRef:
      namespace: default
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: pvc-backup
    sessionHistoryLimit: 3
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: pvc-demo
      backend: s3-storage
      directory: /pvc-backup-demo
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: default
      deletionPolicy: WipeOut 
    addon:
      name: pvc-addon
      tasks:
      - name: PhysicalBackup
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0
    retryConfig:
      maxRetry: 2
      delay: 1m