apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: mssql-db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MSSQLServer
    namespace: demo
    name: mssqlserver-ag
  backends:
    - name: gcs-backend
      storageRef:
        namespace: demo
        name: gcs-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 1
      scheduler:
        schedule: "*/2 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: gcs-mssql-repo
          backend: gcs-backend
          directory: /mssql
          encryptionSecret:
           name: encrypt-secret
           namespace: demo
        # - name: gcs-mssql-repo2
        #   backend: gcs-backend
        #   directory: /mssql2
        #   encryptionSecret:
        #    name: encrypt-secret
        #    namespace: demo
      addon:
        name: mssqlserver-addon
        jobTemplate:
          spec:
            securityContext:
              runAsUser: 0
        tasks:
          - name: logical-backup
            params:
             # databases: Dummy