apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-mssql-restore
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MSSQLServer
    namespace: demo
    # name: restored-mssqlserver-ag
    name: mssqlserver-ag
  dataSource:
    repository: gcs-mssqlserver-ag-repo
    snapshot: latest
  addon:
    name: mssqlserver-addon
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 0
    tasks:
      - name: logical-backup-restore