apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restoresession
  namespace: demo
spec:
  manifestOptions:
    restoreNamespace: demo
    mongoDB:
      db: true
      dbName: new-mongodb
      authSecret: true
      authSecretName: new-mongodb-se
      configSecret: true
  dataSource:
    snapshot: latest
    repository: gcs-mongo-repo
    encryptionSecret:
      name: encry-secret
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
      - name: manifest-restore