apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: restore-sts-pvc-from-volumesnapshot
  namespace: a
spec:
  dataSource:
    namespace: demo
    repository: sts-volume-snapshot-driver-vs
    snapshot: latest
    encryptionSecret:
      name: encryption-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: volume-snapshot-restore
      targetVolumes:  
        volumeClaimTemplates:
        - metadata:
            name: restore-data-${POD_ORDINAL} 
          spec:
            accessModes: [ "ReadWriteOnce" ]
            # storageClassName: "csi-gce-pd"
            resources:
              requests:
                storage: 1Gi
        - metadata:
            name: restore-config-${POD_ORDINAL}
          spec:
            accessModes: [ "ReadWriteOnce" ]
            # storageClassName: "csi-gce-pd"
            resources:
              requests:
                storage: 1Gi
            