apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: clone-pvc-restoresession
  namespace: demo-test
spec:
  dataSource:
    namespace: demo
    repository: statefulset-backup
    snapshot: latest
    encryptionSecret:
      name: encryption-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: volume-clone
      targetVolumes:
        volumeMounts:
        - name:  restore-data-restore-demo
          mountPath:  /source/data
        - name:  restore-config-restore-demo
          mountPath:  /source/config  
        volumeClaimTemplates:
        - metadata:
            name: restore-data-restore-demo-${POD_ORDINAL} # In Resolver func Need to Create PVC by this Name.
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "standard"
            resources:
              requests:
                storage: 2Gi
        - metadata:
            name: restore-config-restore-demo-${POD_ORDINAL} # In Resolver func Need to Create PVC by this Name.
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "standard"
            resources:
              requests:
                storage: 2Gi