# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: host-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/stash-test"


# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: demo
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: demo-pod-1
  namespace: demo
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c","truncate -s 10GB sample/data/10gi.gb && sleep 3000"]
    volumeMounts:
    - name: my-volume
      mountPath: /sample/data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: host-pvc


