apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: restore-statefulset
  namespace: demo
spec:
  dataSource:
    repository: statefulset-backup
    snapshot: latest
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: clone-pvc-restore
      targetVolumes:
        volumeMounts:
        - name:  restore-data-restore-demo
          mountPath:  /source/data
        - name:  restore-config-restore-demo
          mountPath:  /source/config  
        volumeClaimTemplates:
        - metadata:
            name: restore-data-restore-demo-${POD_ORDINAL} 
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "standard"
            resources:
              requests:
                storage: 2Gi
        - metadata:
            name: restore-config-restore-demo-${POD_ORDINAL} 
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "standard"
            resources:
              requests:
                storage: 2Gi