apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: restored-es
  namespace: demo
spec:
  enableSSL: true
  replicas: 1
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  init:
    waitForInitialRestore: true
  storageType: Durable
  terminationPolicy: Delete
  version: xpack-8.11.1