apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: mssql-addon
spec:
  backupTasks:
    - name: logical-backup
      function: mssql-backup
      driver: Restic
      executor: Job
      singleton: true
      parameters:
        - name: args
          usage: Arguments to be passed to the dump command.
          required: false
        - name: databases
          usage: List of databases to backup.
          required: false
        - name: enableCache
          usage: Enable or disable caching. Disabling caching may impact backup performance.
          required: false
          default: "true"
        - name: scratchDir
          usage: Directory for holding temporary files and restic cache.
          required: false
          default: /kubestash-tmp
        - name: interimStorage
          usage:  Intermediate backupStorage to store backup/restore file.
          required: true
        - name: interimDataDir
          usage: Directory where data will be stored temporarily before uploading to the backend.
          required: false
          default: /kubestash-interim/data
      volumeTemplate:
        - name: kubestash-tmp-volume
          usage: Holds temporary files and restic cache.
          source:
            emptyDir: {}
        - name: kubestash-interim-volume
          usage: Holds backed up data temporarily before uploading to the backend.
          source:
            emptyDir: {}  
      volumeMounts:
        - name: kubestash-tmp-volume
          mountPath: /kubestash-tmp
        - name: kubestash-interim-volume
          mountPath: /kubestash-interim
  restoreTasks:
    - name: logical-backup-restore
      function: mssql-restore
      driver: Restic
      executor: Job
      singleton: true
      parameters:
        - name: args
          usage: Arguments to be passed to the dump command.
          required: false
          # default: WITH REPLACE, RECOVERY
        - name: databases
          usage: List of databases to restore.
          required: false
        - name: enableCache
          usage: Enable or disable caching. Disabling caching may impact backup performance.
          required: false
          default: "true"
        - name: scratchDir
          usage: Directory for holding temporary files and restic cache.
          required: false
          default: /kubestash-tmp
        - name: interimStorage
          usage:  Intermediate backupStorage to store backup/restore file.
          required: true
        - name: interimDataDir
          usage: Directory where data will be stored temporarily before uploading to the backend.
          required: false
          default: /kubestash-interim/data
      volumeTemplate:
        - name: kubestash-tmp-volume
          usage: Holds temporary files and restic cache.
          source:
            emptyDir: {}
        - name: kubestash-interim-volume
          usage: Holds backed up data temporarily before uploading to the backend.
          source:
            emptyDir: {}
      volumeMounts:
        - name: kubestash-tmp-volume
          mountPath: /kubestash-tmp
        - name: kubestash-interim-volume
          mountPath: /kubestash-interim
