apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: mssql-db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MsSQL
    namespace: demo
    name: sample
  backends:
    - name: gcs-backend
      storageRef:
        namespace: demo
        name: gcs-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/1 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: gcs-mssql-repo
          backend: gcs-backend
          directory: /mssql
          encryptionSecret:
           name: encrypt-secret
           namespace: demo
      addon:
        name: mssql-addon
        tasks:
          - name: logical-backup