apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: mssql-db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MSSQLServer
    namespace: demo
    name: sample-mssql
  backends:
    - name: s3-backend
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 3
      scheduler:
        schedule: "*/1 * * * *"
        successfulJobsHistoryLimit: 1
        failedJobsHistoryLimit: 1
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: s3-mssql-repo
          backend: s3-backend
          directory: /mssql
          encryptionSecret:
           name: encrypt-secret
           namespace: demo
      addon:
        name: mssql-addon
        tasks:
          - name: logical-backup
            params:
             databases: dummy
             args: WITH FORMAT, COMPRESSION
             interimStorage: demo/azure-storage
            addonVolumes:
              - name: kubestash-interim-volume
                source:
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                      - ReadWriteOnce