apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mssql-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --mssql-args=${args:=}
  image: anisurrahman75/mssql-restic-plugin:init-backup-restore_linux_amd64