apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mssql-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --mssql-args=${args:=}
  - --databases=${databases:=}
  - --interim-storage=${interimStorage:=}
  image: anisurrahman75/mssql-restic-plugin:init-backup-restore_linux_amd64

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mssql-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --mssql-args=${args:=}
  - --databases=${databases:=}
  - --interim-storage=${interimStorage:=}
  image: anisurrahman75/mssql-restic-plugin:init-backup-restore_linux_amd64