apiVersion: kubedb.com/v1alpha2
kind: MsSQL
metadata:
  name: restored-sample-mssql
  namespace: demo
spec:
  version: "2022-cu12"  # Specify the desired version, e.g., "2019-CU12-GDR" or "2017-CU24-GDR"
  replicas: 2        # Number of instances to deploy
  authSecret:
    name: mssql-custom-auth
    externallyManaged: true
  internalAuth:
    endpointCert:
      issuerRef:
        apiGroup: cert-manager.io
        name: mssql-ca-issuer
        kind: Issuer
  topology:
    mode: AvailabilityGroup
    availabilityGroup:
      databases:
        - AgDB1
        - AgDB2
  leaderElection:
    period: 100ms
    electionTick: 10
    heartbeatTick: 1
    transferLeadershipInterval: 1s
    transferLeadershipTimeout: 60s
  storageType: Durable
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete # Halt
