apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-mssql-restore
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MSSQLServer
    namespace: demo
    name: sample-mssql
  dataSource:
    snapshot: latest
    repository: azure-mssql-repo
    encryptionSecret:
      name: encrypt-secret 
      namespace: demo
  addon:
    name: mssql-addon
    tasks:
      - name: logical-backup-restore
        params:
          databases: dummy
          interimStorage: demo/azure-storage
          # args: WITH RECOVERY, REPLACE
        addonVolumes:
          - name: kubestash-interim-volume
            source:
              volumeClaimTemplate:
                spec:
                  accessModes:
                  - ReadWriteOnce