apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: kubestash-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 3000
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
        - mountPath: /source/config
          name: source-config
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: restored-source-data
      - name: source-config
        persistentVolumeClaim:
          claimName: restored-source-config