apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-volume-snapshot-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: target-pvc
    namespace: demo
  backends:
  - name: gcs-storage
    storageRef:
      namespace: demo
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: pvc-volume-snapshot-backup
    sessionHistoryLimit: 
    scheduler: # CronJob specification
      schedule: "*/5 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: pvc-demo-volume-snapshot
      backend: gcs-storage
      directory: /pvc-volume-snapshot
      deletionPolicy: WipeOut 
    addon:
      name: pvc-addon
      tasks:
      - name: volume-snapshot
        params:
          volumeSnapshotClassName: longhorn
