apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: restore-pvc-from-volumesnapshot
  namespace: demo
spec:
  dataSource:
    repository: pvc-demo-volume-snapshot
    snapshot: latest
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: pvc-addon
    tasks:
    - name: VolumeSnapshotRestore
      targetVolumes:  
        volumeClaimTemplates:
        - metadata:
            name: restore-data-restore-pvc 
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "csi-standard-immediate"
            resources:
              requests:
                storage: 10Gi
            