apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: db-mongo-appbinding
  namespace: demo
spec:
  clientConfig:
    url: mongodb+srv://stash-test.38r1r.mongodb.net/
  secret:
    name: db-mongo-credentials-secret
  type: mongodb