apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mongo-restore
  namespace: demo
spec:
  repository:
    name: gcs-repo
  task:
    name: mongodb-restore-6.0.5
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: db-mongo-appbinding
  rules:
    - snapshots: [latest]