apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: demo-retention
  namespace: demo
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 3
  failedSnapshots:
    last: 3
  usagePolicy:
    allowedNamespaces:
      from: All
 
