apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: demo-retention
  namespace: demo3
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 1
  usagePolicy:
    allowedNamespaces:
      from: All
