apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-standard-immediate
parameters:
  type: pd-standard
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate