apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-mssql-restore
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MSSQLServer
    namespace: demo
    name: mssqlserver-ag
  dataSource:
    snapshot: latest
    repository: gcs-mssql-repo
    encryptionSecret:
      name: encrypt-secret 
      namespace: demo
  addon:
    name: mssql-addon
    tasks:
      - name: logical-backup-restore
        params:
          # databases: agdb1