apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: volume-snapshot-backup
  namespace: default
spec:
  target:
    apiGroup: apps
    kind: Deployment
    namespace: default
    name: kubestash-deployment
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: default
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: default
  sessions:
  - name: deployment-volume-snapshot-backup
    sessionHistoryLimit: 
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: deployment-volume-snapshot
      backend: s3-storage
      directory: /dep-volume-snapshot
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: default
      deletionPolicy: WipeOut 
    addon:
      name: volume-snapshot-addon
      tasks:
      - name: workload-volume-snapshot-backup
        params:
          snapshotClassName: longhorn
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0
    retryConfig:
      maxRetry: 2
      delay: 1m