apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: volume-snapshot-backup-deploy
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: Deployment
    namespace: demo
    name: kubestash-deployment
  backends:
  - name: gcs-storage
    storageRef:
      namespace: demo
      name: gcs-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: deployment-volume-snapshot-backup
    sessionHistoryLimit: 
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: deployment-volume-snapshot
      backend: gcs-storage
      directory: /dep-volume-snapshot-vs
      encryptionSecret:
       name: encry-secret # some addon may not support encryption
       namespace: demo
      deletionPolicy: WipeOut 
    addon:
      name: workload-addon
      tasks:
      - name: VolumeSnapshot
        params:
          # snapshotClassName: longhorn
      jobTemplate:
        spec: 
          securityContext: 
            runAsUser: 0
    retryConfig:
      maxRetry: 2
      delay: 1m