apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: restore-dep-pvc-from-volumesnapshot
  namespace: default
spec:
  dataSource:
    repository: deployment-volume-snapshot
    snapshot: latest
    encryptionSecret:
      name: encry-secret # some addon may not support encryption
      namespace: default
  addon:
    name: volume-snapshot-addon
    tasks:
    - name: workload-volume-snapshot-restore
      targetVolumes:  
        volumeClaimTemplates:
        - metadata:
            name: restore-source-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "longhorn"
            resources:
              requests:
                storage: 2Gi
        - metadata:
            name: restore-source-config
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "linode-block-storage-retain"
            resources:
              requests:
                storage: 2Gi