apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: statefulset-backup
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    namespace: demo
    name: kubestash-demo
  backends:
    - name: s3-storage
      storageRef:
        apiGroup: storage.kubestash.com
        namespace: demo
        kind: BackupStorage
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: workload-backup
      sessionHistoryLimit: 5
      scheduler: 
        schedule: "*/2 * * * *"
        jobTemplate: 
          backoffLimit: 1
      repositories: 
        - name: statefulset-backup
          backend: s3-storage
          directory: /statefulset
          encryptionSecret:
           name: encry-secret
           namespace: demo
          deletionPolicy: WipeOut 
      addon:
        name: workload-addon
        tasks:
          - name: workload-backup 
            params:
             paths: /source/data,/source/config
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
      retryConfig:
        maxRetry: 2
        delay: 1m
