apiVersion: v1
kind: Pod
metadata:
  name: mariadb-client
  namespace: mariadb
spec:
  containers:
  - name: mariadb-client
    image: docker.io/bitnami/mariadb:11.4.3-debian-12-r1
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity;"]  # Keep the pod running
    securityContext:
      runAsUser: 0  # Run as root
  restartPolicy: Never