apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: mariadb-restoresession
  namespace: demo
spec:
  target:
    apiGroup: appcatalog.appscode.com
    kind: AppBinding
    name: db-mariadb-appbinding
    namespace: demo
  dataSource:
    repository: gcs-mariadb-repo
    snapshot: latest
    encryptionSecret:
      name: encrypt-secret
      namespace: demo
  addon:
    name: mariadb-addon
    tasks:
      - name: logical-backup-restore