apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: mongodb-restoresession
  namespace: demo
spec:
  # target:
  #   name: restored-mongodb
  #   namespace: demo
  #   apiGroup: kubedb.com
  #   kind: MongoDB
  dataSource:
    snapshot: latest
    repository: gcs-mongo-repo
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
      - name: LogicalBackupRestore